Update patch set 6
Patch Set 6:

build failed if device lives in its own soong namespace:

```
error: system/core/init/Android.bp:95:1: "libinit" depends on undefined module "libinit_oneplus3"
Module "libinit" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "libinit_oneplus3" can be found in these namespaces: ["device/oneplus/oneplus3"]
```

Patch-set: 6
Reviewer: Gerrit User 10258 <10258@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>