[DNM] Squash of lineage-16.0-pie-gsi
Squashed commit of the following:

commit ca7c586b6924c7bd3b414fb39d8cef2572dd88e8
Merge: 8aadd340d cf0aec92b
Author: Treehugger Robot <treehugger-gerrit@google.com>
Date:   Thu Jun 13 16:34:35 2019 +0000

    Merge "tombstoned: fixed tombstones failed issue" into pie-gsi

commit cf0aec92bd36e0e90b88b05d479a98f4b1638bf1
Author: Jinguang Dong <dongjinguang@huawei.com>
Date:   Sat Nov 24 17:12:33 2018 +0800

    tombstoned: fixed tombstones failed issue

    There is a problem about tombstone, which it will fail to
    generate tombstone file in some scenarios due to socket
    communication exception.

    Reproduce step:
    step 1: reboot device
    step 2: ps -ef |grep zygote , get the pid of zygote64
    (Attention: zygote64 should never been killed or reboot,
    otherwise we can get the tombstone file)
    step 3: kill -5 pid of zygote64
    step 4: cd data/tombstones/, and could not find the tombstone
    file of zygote64.

    [Cause Analysis]
    1. There are following logs by logcat:
    11-19 15:38:43.789   569   569 F libc : Fatal signal 5 (SIGTRAP),
    code 0 (SI_USER) in tid 569 (main), pid 569 (main)
    11-19 15:38:43.829  6115  6115 I crash_dump64: obtaining output
    fd from tombstoned, type: kDebuggerdTombstone
    11-19 15:38:43.830   569  5836 I Zygote  : Process 6114 exited
    cleanly (0)
    11-19 15:38:43.830   777   777 I /system/bin/tombstoned: received
    crash request for pid 569
    11-19 15:38:43.831  6115  6115 I crash_dump64: performing dump of
    process 569 (target tid = 569)
    ...
    11-19 15:38:43.937   777   777 W /system/bin/tombstoned: crash
    socket received short read of length 0 (expected 12)
    2. The last log was print by function of crash_request_cb in
    file of tombstoned.cpp, following related code:
      rc = TEMP_FAILURE_RETRY(read(sockfd, &request, sizeof(request)));
      if (rc == -1) {
        PLOG(WARNING) << "failed to read from crash socket";
        goto fail;
      } else if (rc != sizeof(request)) {
        LOG(WARNING) << "crash socket received short read of length " << rc << " (expected "
                     << sizeof(request) << ")";
        goto fail;
      }

    Tombstoned read message by socket, and now the message length is
    zero. Some socket communication exception occurs at that time.
    We try to let crash_dump resend the socket message when the
    communication is abnormal. Just as this CL.

    Test: 1 reboot device
          2 ps -ef |grep zygote , get the pid of zygote64
           (Attention: zygote64 should never been killed or reboot,
           otherwise we can get the tombstone file)
          3 kill -5 pid of zygote64
          4 cd data/tombstones/, and could find the tombstone file of
           zygote64.

    Change-Id: Ic152b081024d6c12f757927079fd221b63445b18
    (cherry picked from commit 8ac2f27cc2fa5fbfc1bbd1cede906d254a77f862)

commit 8aadd340df213a3013bf94dfc2ba18aeaebaa3d8
Merge: c7902e72b 63b2808f7
Author: Treehugger Robot <treehugger-gerrit@google.com>
Date:   Fri May 17 01:53:54 2019 +0000

    Merge changes I6cd5701b,If83ac1d6 into pie-gsi

    * changes:
      health: Add CAP_WAKE_ALARM to service via init
      Fix two clang-tidy issues in crasher.cpp.

commit c7902e72b7f590662962449aaa1dc3e2155b6f99
Merge: c8a78b58f 89008cd5f
Author: Treehugger Robot <treehugger-gerrit@google.com>
Date:   Fri May 17 01:48:47 2019 +0000

    Merge "Add native vsock support to ADB." into pie-gsi

commit 63b2808f77135ce0db431ab7c79919463b4c9690
Author: Felix <google@ix5.org>
Date:   Fri Jan 4 02:24:41 2019 +0100

    health: Add CAP_WAKE_ALARM to service via init

    platform/interfaces/health/2.0/default/healthd_common.cpp wants to use
    timerfd_create() to register a wakealarm.

    To use the timerfd_create() syscall with CLOCK_BOOTTIME_ALARM,
    CAP_WAKE_ALARM is needed.

    Since the .rc file for android.hardware.health@2.0 is shipped here in
    system/core, update it here.

    Signed-off-by: Felix <google@ix5.org>
    Change-Id: I6cd5701b6e5cac37eb021d894251a3a9dc590b95
    (cherry picked from commit fb55955462ac90023c88c24de090937342b28d52)

commit 89008cd5f3b2d156fb1d3082b19af67275e2bbf9
Author: Cody Schuffelen <schuffelen@google.com>
Date:   Fri Dec 21 13:39:36 2018 -0800

    Add native vsock support to ADB.

    vsock is a socket address family for communicating into and out of
    virtual machines. Addresses have a port and CID. The CID is unique to
    each virtual machine on the computer. The VM host always has CID 2.
    http://man7.org/linux/man-pages/man7/vsock.7.html

    Inside the android guest, the adb daemon hosts a vsock server with
    VMADDR_CID_ANY, automatically using the guest CID. The adb server
    can now connect to addresses of the form vsock:cid:port, where the CID
    must be specified and the port defaults to 5555.

    This is a significant speed improvement for ADB connections in
    Cuttlefish, with 150-200 MB/s for `adb push` and 100-150 MB/s for
    `adb pull`. It also allows removing some proxying steps from Cuttlefish,
    simplifying the full connection path, and removes a dependency on the
    unstable ivshmem protocol.

    Commands tested against a Cuttlefish VM with CID 3:
    adb connect vsock:3:5555
    adb -s vsock:3:5555 shell
    adb disconnect vsock:3:5555

    Supporting "adb disconnect" and "adb -s" required modifying some of the
    parts that parse addresses / serials.

    push/pull trials with native adb vsock support in cuttlefish:

    100m: 1 file pushed. 167.9 MB/s (104857600 bytes in 0.596s)
    100m: 1 file pushed. 171.1 MB/s (104857600 bytes in 0.584s)
    100m: 1 file pushed. 175.2 MB/s (104857600 bytes in 0.571s)
    100m: 1 file pushed. 168.7 MB/s (104857600 bytes in 0.593s)
    100m: 1 file pushed. 172.9 MB/s (104857600 bytes in 0.578s)
    100m: 1 file pushed. 168.8 MB/s (104857600 bytes in 0.592s)
    100m: 1 file pushed. 197.5 MB/s (104857600 bytes in 0.506s)
    100m: 1 file pushed. 201.0 MB/s (104857600 bytes in 0.497s)
    100m: 1 file pushed. 199.0 MB/s (104857600 bytes in 0.503s)
    100m: 1 file pushed. 215.5 MB/s (104857600 bytes in 0.464s)

    /data/local/tmp/100m: 1 file pulled. 143.8 MB/s (104857600 bytes in 0.696s)
    /data/local/tmp/100m: 1 file pulled. 137.5 MB/s (104857600 bytes in 0.727s)
    /data/local/tmp/100m: 1 file pulled. 135.5 MB/s (104857600 bytes in 0.738s)
    /data/local/tmp/100m: 1 file pulled. 139.6 MB/s (104857600 bytes in 0.716s)
    /data/local/tmp/100m: 1 file pulled. 158.3 MB/s (104857600 bytes in 0.632s)
    /data/local/tmp/100m: 1 file pulled. 126.7 MB/s (104857600 bytes in 0.789s)
    /data/local/tmp/100m: 1 file pulled. 129.8 MB/s (104857600 bytes in 0.771s)
    /data/local/tmp/100m: 1 file pulled. 154.8 MB/s (104857600 bytes in 0.646s)
    /data/local/tmp/100m: 1 file pulled. 156.9 MB/s (104857600 bytes in 0.637s)
    /data/local/tmp/100m: 1 file pulled. 152.2 MB/s (104857600 bytes in 0.657s)

    Bug: 121166534
    Change-Id: I50f21fb5c9acafb8daa789df4e28c9e1bbbbf2ef
    Test: adb connect/shell/disconnect

commit a529407808aceee814ca86cf63cb2c8a9c36903f
Author: Ram Muthiah <rammuthiah@google.com>
Date:   Fri Apr 26 12:45:14 2019 -0700

    Fix two clang-tidy issues in crasher.cpp.

    --------------------------
    pie-cuttlefish-testing broke on ASAN due to errors in the crasher
    binary. Cherry-picking in the fix from master system/core

    out/soong/.intermediates/system/core/debuggerd/crasher/crasher/
    android_x86_core_asan/obj/system/core/debuggerd/crasher/crasher.o
    system/core/debuggerd/crasher/crasher.cpp system/core/debuggerd/
    crasher/crasher.cpp:260:9: error: use of undeclared identifier
    '__read_chk' __read_chk(-1, buf, 32, 10);
    --------------------------

    TEMP_FAILURE_RETRY's result was unused for the call to read(), so now
    mark it as such to silence a possible unused result warning. For
    __read_chk(), this function is an internal implementation detail of
    FORTIFY in Bionic. Under clang-tidy, FORTIFY checks are actually
    removed, so this now results in an unknown function being called. The
    code should not be explicitly depending on an implementation detail, but
    we can just suppress the failing case to retain test coverage of the
    actual implementation.

    Bug: http://b/110779387
    Test: Build using WITH_TIDY=1
    Change-Id: If83ac1d6f3b6dc32c0d0fb56d8e675e53b586f78

commit c8a78b58f94e208526e9d55c64891991496dba93
Merge: 030b669b1 d9ef345d4
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Mon May 13 21:21:09 2019 +0000

    Merge "Snap for 5450365 from e6ef013d2c8c1201540128d9961b73450257ab90 to pi-platform-release am: 50e44460e7" into pie-gsi

commit d9ef345d4f95db8193b66ec88d0f112d0b678c1d
Merge: 030b669b1 50e44460e
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Mon May 13 14:20:59 2019 -0700

    Snap for 5450365 from e6ef013d2c8c1201540128d9961b73450257ab90 to pi-platform-release
    am: 50e44460e7

    Change-Id: I0c31ad85ae76eb2c3d5384521313d53b8e498228

commit 50e44460e76c950df2ae58ada53a86ba74f1fdc9
Merge: 5d1d32dcb e6ef013d2
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Tue May 7 22:04:02 2019 +0000

    Snap for 5450365 from e6ef013d2c8c1201540128d9961b73450257ab90 to pi-platform-release

    Change-Id: I51d6a1b331634e927247a13a96bfdd10d4e00f4f

commit 030b669b10db0c0ad2dd9b0c53a37cf68711caaa
Merge: cf07c8b4a d8050644d
Author: Treehugger Robot <treehugger-gerrit@google.com>
Date:   Mon Mar 18 12:50:22 2019 +0000

    Merge "fs_mgr_fstab: Add Adiantum support" into pie-gsi

commit d8050644d30dcbb2a59c2267530de742e5420833
Author: Greg Kaiser <gkaiser@google.com>
Date:   Mon Dec 3 12:30:42 2018 -0800

    fs_mgr_fstab: Add Adiantum support

    Adiantum is a crypto method Android is supporting for devices
    which don't have AES CPU instructions.  See the paper
    "Adiantum: length-preserving encryption for entry-level processors"
    (https://eprint.iacr.org/2018/720.pdf) for more details.

    We add Adiantum to our list of supported encryption modes.

    Bug: 112010205
    Test: Tested on a device
    Change-Id: I14a400164803a1e217d378ad9bd8b67a61b8b7d0
    Merged-In: I14a400164803a1e217d378ad9bd8b67a61b8b7d0

commit cf07c8b4ae09b59bcb7d55cc8b0844dcba70474c
Merge: afc32531f abfb8dfe6
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Fri Mar 8 23:39:47 2019 +0000

    Merge "Snap for 5240760 from 20ac1203a3201ac3e6d05a19325f5569033f3d08 to pi-platform-release am: 5d1d32dcbf" into pie-gsi

commit abfb8dfe6ce84d70d61da3eebf1cf6ce53b52fd8
Merge: afc32531f 5d1d32dcb
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Fri Mar 8 15:39:36 2019 -0800

    Snap for 5240760 from 20ac1203a3201ac3e6d05a19325f5569033f3d08 to pi-platform-release
    am: 5d1d32dcbf

    Change-Id: I85d3f87972bf741a25389a0ecc1c64261833a922

commit 5d1d32dcbffaede882c140ce5f00502135cd3f7e
Merge: ba36715af 20ac1203a
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Fri Mar 8 18:40:29 2019 +0000

    Snap for 5240760 from 20ac1203a3201ac3e6d05a19325f5569033f3d08 to pi-platform-release

    Change-Id: I6bbede2f8c74a9f344df6f3c713de709eb79cd26

commit afc32531f6c2ee29e6840d76543e63f64477e03d
Merge: 643fa4698 1cdb8762f
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Mon Feb 11 23:08:35 2019 +0000

    Merge "Snap for 5180536 from cddcc0d9cf7cbba53e54d67455737a3900ae5d9f to pi-platform-release am: ba36715afc" into pie-gsi

commit 1cdb8762fd2e66667e9f9524be83f45dc730f588
Merge: 643fa4698 ba36715af
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Mon Feb 11 15:08:29 2019 -0800

    Snap for 5180536 from cddcc0d9cf7cbba53e54d67455737a3900ae5d9f to pi-platform-release
    am: ba36715afc

    Change-Id: I5677e6045f70d1520e36613454dfdc1214100b41

commit ba36715afc3f79ce9f954486373e7c4da32bae19
Merge: 83cda925e cddcc0d9c
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Sat Feb 9 02:22:24 2019 +0000

    Snap for 5180536 from cddcc0d9cf7cbba53e54d67455737a3900ae5d9f to pi-platform-release

    Change-Id: Ie01971579962cce36d3170df9c1cb09f8b152520

commit 643fa4698160c5806e644b54fb9a96898ba8c34a
Merge: 3ca242b62 8c188e472
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Tue Jan 15 01:00:22 2019 +0000

    Merge "Merge cherrypicks of [5929407, 5929627, 5929597, 5929598] into pi-platform-release am: 83cda925e1" into pie-gsi

commit 8c188e47226a4acce90473b2f5870aabb530e807
Merge: 3ca242b62 83cda925e
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Mon Jan 14 17:00:16 2019 -0800

    Merge cherrypicks of [5929407, 5929627, 5929597, 5929598] into pi-platform-release
    am: 83cda925e1

    Change-Id: Iaff261ba28c974de7b35e84af43c79d43c2d83d5

commit 83cda925e1160d3bfc7595d3e7a74fc62a580178
Merge: 25f1ac6be 7c932e95c
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Thu Jan 3 23:49:30 2019 +0000

    Merge cherrypicks of [5929407, 5929627, 5929597, 5929598] into pi-platform-release

    Change-Id: I96a4dbe887b725b458061cfc5d64b42f2e554038

commit 7c932e95c340e62ce78233b198362f200794d2f8
Author: Greg Kaiser <gkaiser@google.com>
Date:   Mon Dec 3 12:30:42 2018 -0800

    fs_mgr_fstab: Add Adiantum support

    Adiantum is a crypto method Android is supporting for devices
    which don't have AES CPU instructions.  See the paper
    "Adiantum: length-preserving encryption for entry-level processors"
    (https://eprint.iacr.org/2018/720.pdf) for more details.

    We add Adiantum to our list of supported encryption modes.

    Bug: 112010205
    Test: Tested on a device
    Change-Id: I14a400164803a1e217d378ad9bd8b67a61b8b7d0
    Merged-In: I14a400164803a1e217d378ad9bd8b67a61b8b7d0
    (cherry picked from commit 1b3082642af6f846eb9bcd4fb5c001eed2cfd8a4)

commit 3ca242b6217663ce002e20030cc3c37341fa65cc
Merge: 364fb0e47 e563b2c81
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Fri Dec 7 06:37:13 2018 +0000

    Merge "Merge PQ1A.181205.006 from Pi-QPR1-Release into ToT for Pi-Platform release.\n\nBUG: 120448245 am: 25f1ac6be2" into pie-gsi

commit e563b2c818cc1a4142225eb08fcbf4a2ba436e3e
Merge: 364fb0e47 25f1ac6be
Author: Bill Rassieur <rassb@google.com>
Date:   Thu Dec 6 22:37:07 2018 -0800

    Merge PQ1A.181205.006 from Pi-QPR1-Release into ToT for Pi-Platform release.\n\nBUG: 120448245
    am: 25f1ac6be2

    Change-Id: Iac0c07e6363c2d09be30455ff3ebbad5df017137

commit 25f1ac6be2a627c2680e95046eced76ace4d74dd
Merge: a17e32ac8 1b94df53d
Author: Bill Rassieur <rassb@google.com>
Date:   Tue Dec 4 17:00:05 2018 +0000

    Merge PQ1A.181205.006 from Pi-QPR1-Release into ToT for Pi-Platform release.\n\nBUG: 120448245

    Change-Id: Ia66dd2a90e074d2fcb0dbaeb424031a41752dd03

commit 364fb0e47faf9fadb9a0f7c0957591e02fbeebc8
Merge: ed732916f c89849ef5
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Fri Nov 30 19:37:48 2018 +0000

    Merge "Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release am: a17e32ac8c" into pie-gsi

commit c89849ef5986238da04bfec55e5d3a112aebf45b
Merge: ed732916f a17e32ac8
Author: Bill Yi <byi@google.com>
Date:   Fri Nov 30 11:37:43 2018 -0800

    Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release
    am: a17e32ac8c

    Change-Id: Ic89321fcd57d67f603fcfec071d65f135e2bc3c4

commit a17e32ac8ce47bd09b0cc76eff5af0ef0184252a
Merge: 4da9048b8 1797c6976
Author: Bill Yi <byi@google.com>
Date:   Wed Nov 28 18:35:04 2018 -0800

    Merge pi-qpr1-release PQ1A.181105.017.A1 to pi-platform-release

    Change-Id: I71c020e283326cc9ae8bb99fcea83e32c98c6e6d

commit ed732916f9387ac9885d87d89b652c26e17e66fa
Merge: f5840af75 c34430b5c
Author: Android Merger <noreply-android-build-merger@google.com>
Date:   Wed Oct 17 04:26:20 2018 +0000

    Merge "Merge PPR2.181005.003 from pi-release-2 into pi-platform-release. am: 4da9048b80" into pie-gsi

commit c34430b5ca84dec4c9d8061b061c486defa97eb5
Merge: f5840af75 4da9048b8
Author: Bill Rassieur <rassb@google.com>
Date:   Tue Oct 16 21:26:14 2018 -0700

    Merge PPR2.181005.003 from pi-release-2 into pi-platform-release.
    am: 4da9048b80

    Change-Id: I9c98450fb761edc9dbf76d3f656ec92e719673c7

commit 4da9048b80708d978636e8afed084f621f185719
Merge: 0fac9018f c9602275f
Author: Bill Rassieur <rassb@google.com>
Date:   Wed Oct 10 17:27:51 2018 +0000

    Merge PPR2.181005.003 from pi-release-2 into pi-platform-release.

    Change-Id: I398364a59b493057139bdfd5de6b5070978c44bb
    BUG: 117431430

Change-Id: Id5797317cbac2e20f4bf2612f7bcdd4fc655a27b