Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> How is fd_set defined on windows?  Does it really use uint64_t?
> 
> The client code uses adb_poll() which is already platform agnostic.  Perhaps we should convert to using that instead.  See client/file_sync_client.cpp in SyncConnection::ReceivedError() for an example.

>How is fd_set defined on windows?

```
typedef struct fd_set
{
        u_int   fd_count;
        SOCKET  fd_array[FD_SETSIZE];
} fd_set;
```

>Does it really use uint64_t?
No, it's using 'SOCKET' which ends up being 'unsigned int' thus I thought that using uint64_t for device_fd so that we won't overflow would be safe here.

```
system/core/adb/client/commandline.cpp:914:9: error: comparison of integers of different signs: 'SOCKET' (aka 'unsigned
 int') and 'int' [-Werror,-Wsign-compare]
        FD_SET(device_fd, &fds);
        ^~~~~~~~~~~~~~~~~~~~~~~
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/psdk_inc/_fd_types.h:77:40: note: expand
ed from macro 'FD_SET'
                if (((fd_set *)(set))->fd_array[__i] == (fd)) {         \
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
1 error generated.
```

Patch-set: 1
Reviewer: Gerrit User 10067 <10067@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>